general:
  # Exporter Listening Address and Port
  # address: 0.0.0.0 # Optional
  # port: 7100 # Optional
  # Exporter Metrics Path
  # path: /metrics # Optional

auth:
  # Basic Auth
  # username: user # Optional
  # password: pass # Optional
  # Bearer Token
  # token: token # Optional

sonarr:
  url: http://sonarr:8989
  api_key: key
  # alias: sonarr # Optional to Differentiate between multiple Services
  # api_version: v3 # Optional to use a different API Version
  # interval: 30 # Optional to set a different Interval in Seconds
  # detailed: true  # Get Data per Series

radarr:
  url: http://radarr:7878
  api_key: key
  # alias: radarr # Optional to Differentiate between multiple Services
  # api_version: v3 # Optional to use a different API Version
  # interval: 30 # Optional to set a different Interval in Seconds
  # detailed: true  # Get Data per Movie

prowlarr:
  url: http://prowlarr:9696
  api_key: key
  # alias: prowlarr # Optional to Differentiate between multiple Services
  # api_version: v1 # Optional to use a different API Version
  # interval: 30 # Optional to set a different Interval in Seconds
  # detailed: true  # Get Data per Application/Indexer

bazarr:
  url: http://bazarr:6767
  api_key: key
  # alias: bazarr # Optional to Differentiate between multiple Services
  # interval: 30 # Optional to set a different Interval in Seconds
  # detailed: true  # Get Data per Series

readarr:
  url: http://readarr:
  api_key: key
  # alias: prowlarr # Optional to Differentiate between multiple Services
  # api_version: v1 # Optional to use a different API Version
  # interval: 30 # Optional to set a different Interval in Seconds
  # detailed: true  # Get Data per Book
